### ISSUE TITLE
Lets consider making an Appliance monorepo

### ISSUE THREAD

**Issue by slifty** [tvkitchen/appliances#11]
#### What do you want to talk about?
Now that we're [experts in monorepos](github.com/tvkitchen/base) I think we should consider using the monorepo structure for TVK Appliances.

This won't prevent others from writing their own appliances (we would still export each appliance as its own npm package and they would be loaded into TVK from npm)) but it would have the following benefits:

1. Officially supported / maintained TV Kitchen appliances would have a common home.
2. If we change something about the appliance structure, we would be able to update all appliances at once.
3. We'd avoid having a million `appliance-BLAH` repositories.

If we go down this path I would suggest we use *this* repository as the monorepo.  Rename it to `appliances` and move the current package to a `core` folder.

We could then either make the `mock` appliance or the `caption` appliance (or both).

#### Relevant Resources / Research
Here's a link to our [previous monorepo discussions](https://github.com/tvkitchen/base/issues/9)

**Comment by chriszs** [comment]
That seems like a reasonable way to go. [Rollup/plugins](https://github.com/rollup/plugins) comes to mind as the most recent project I encountered which decided to do this.

**Comment by slifty** [comment]
Oh that's an excellent link -- will check it and try to get some inspiration.

**Comment by slifty** [comment]
Closing this since I think we're gonna move in this direction (and indeed there is an open PR #18 )

**Comment by reefdog** [comment]
WAIT I WANT TO WEIGH IN

**Comment by reefdog** [comment]
I agree! Let's do this!
