### ISSUE TITLE
Convert this to a monorepo

### ISSUE THREAD

**Issue by slifty** [tvkitchen/appliances#12]
#### Description
Depending on how #11 discussion goes, we are going to want to turn this into a monorepo.

- [x] rename this repository to `appliances`
- [x] enable yarn packages
- [x] move the appliance-core code to a `packages/core` directory
- [ ] document publication practices

Based on what we learned in the base monorepo, I'm not sure we want or need [lerna](https://www.npmjs.com/package/lerna) for this first implementation.

#### Relevant Resources / Research

- We already went through some of this before over in the [base](github.com/tvkitchen/base) repo.

#### Related Issues
- Issue #11

**Comment by reefdog** [comment]
I came here to ask that we also rename this repo to `appliances` and see it's the first item! 🥳

**Comment by slifty** [comment]
I suppose I should do that *before* we merge the PR!

**Comment by reefdog** [comment]
Prrrrobably? Since you'll have to update a bunch of paths and things? Yeah probably. (But wait, I'm mid-review and no doubt GitHub will roll over and die if you do it now.)

**Comment by slifty** [comment]
TOO LATE

**Comment by reefdog** [comment]
![going-well](https://user-images.githubusercontent.com/4731/84086594-e08d1480-a9ad-11ea-9768-893bb66e62eb.gif)
