### ISSUE TITLE
Should event types live here?

### ISSUE THREAD

**Issue by slifty** [tvkitchen/appliances#9]
#### What do you want to talk about?
Appliances are going to be emitting events. This will be very important to document, name appropriately, and codify in the right place.

For now we're defining those events in this repository, but since those events will be broadcast and consumed outside of appliances alone (e.g. over the socket API, and other parts of the TV Kitchen) it may be more appropriate for them to be stored in the `@tvkitchen/base-constants` package.

Once we nail them down / if folks agree, I'll make a parallel issue over in the base repository.

#### Relevant Resources / Research
None

**Comment by reefdog** [comment]
Very agree; that sort of centralized coordination is what `base-constants` is meant for!

**Comment by slifty** [comment]
This now exists in base-constants.
